# Generated by Django 5.2.6 on 2025-09-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskModel',
        ),
    ]
