# Generated by Django 5.2.6 on 2025-09-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postmodel_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='created_at',
            new_name='created_datetime',
        ),
    ]
