# Generated by Django 5.2.6 on 2025-09-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_created_at_postmodel_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_datetime',
            field=models.DateTimeField(),
        ),
    ]
