# Generated by Django 5.2.6 on 2025-09-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_postmodel_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
