# Generated by Django 5.2.6 on 2025-09-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='PostModel',
        ),
    ]
